# Generated by Django 3.2.6 on 2021-08-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=200)),
                ('age', models.CharField(default='', max_length=200)),
                ('key', models.CharField(default='', max_length=200)),
                ('gender', models.CharField(default='', max_length=200)),

            ],
        ),
        migrations.CreateModel(
            name='StudentDetails1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=200)),
                ('product_key', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
